const express = require('express');
const https = require('https');
const fs = require('fs');

const app = express();
const port = 8080; // Choose any available port

const options = {
  key: fs.readFileSync('key.pem'),    // Read the key file generated by mkcert
  cert: fs.readFileSync('cert.pem'),   // Read the cert file generated by mkcert
};

app.get('/', (req, res) => {
  res.send('Hello, this is a secure server!');
});

https.createServer(options, app).listen(port, () => {
  console.log(`Server running on https://localhost:${port}`);
});
